[build]
  base = "admin-dashboard"
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-vite"

[build.environment]
  VITE_API_BASE = "https://tarel-backend.onrender.com/api"
